[package]
org = "shamlyshanawaz"
name = "police_check_service"
version = "0.1.0"
distribution = "2201.8.4"

[build-options]
observabilityIncluded = true

[persist]
datastore = "mysql"
module = "police_check_service.db"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.2.0"

